# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20180715_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_id',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
