# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
