# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_useredges_edge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
